import Cards from "@/components/Cards";
import Hero from "@/components/Hero";
import Head from "next/head";

import { auth } from "@/firebase/firebase";
import { onAuthStateChanged } from "firebase/auth";
import { useEffect } from "react";
import { userStore } from "@/store/userStore";

export default function Home() {
  const setUsername = userStore((state) => state.setUser);

  useEffect(() => {
    onAuthStateChanged(auth, (user) => {
      if (user) {
        setUsername(user.email);
      } else {
        console.log("no user");
      }
    });
  }, []);

  return (
    <>
      <Head>
        <title>Deals Galore</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Hero />
        <Cards />
      </main>
    </>
  );
}
